### PR TITLE
[sailfishos][embedlite] Adapt partial build script to ESR78

### PR DESCRIPTION
**Pull request by d-grigorev**
This commit edits the path to libxul.so as it has changed since ESR60.

### CODE REVIEW

**Comment by rainemak** [comment]
Adding @spiiroin as he originally wrote the script. Path changes look sensible to me and matches to my recent updates to the https://docs.sailfishos.org/Reference/Core_Areas_and_APIs/Browser/Working_with_Browser/#Partial_builds

**Review by spiiroin — APPROVED** [review]
The commit message could have a bit more info, but after consulting the documentation link: change itself makes sense.

**Comment by d-grigorev** [comment]
> The commit message could have a bit more info, but after consulting the documentation link: change itself makes sense.

I edited the commit message.

**Review by spiiroin — COMMENTED** [review]
lgtm

**Review by rainemak — APPROVED** [review]

**Pull request merged**
