### PR TITLE
ESR 91 changes

### PR DESCRIPTION
**Pull request by llewelld**
This draft PR is for accumulating changes required to support ESR 91.

On this branch the submodule points to a mirror with changes applied directly on top. These changes will need to be turned into patches in this repo before anything is merged.

### CODE REVIEW

**Comment by rainemak** [comment]
Could you point this to the [sailfishos:sailfishos-esr91](https://github.com/sailfishos/gecko-dev/tree/sailfishos-esr91) ? Or how do you see this?

**Comment by pvuorela** [comment]
Suppose this can be closed now?

**Comment by lkraav** [comment]
> Suppose this can be closed now?

In favor of some other PR?

**Comment by mlehtima** [comment]
Changes were already merged in https://github.com/sailfishos/gecko-dev/pull/162

**Pull request closed without merging**
