### PR TITLE
Fix Security info (secure/unsecure) to appear to the toolbar

### PR DESCRIPTION
**Pull request by rainemak**
Contains 3 commits:

1. First one makes it possible to use nsSecureBrowserUI and update it
when location is changed. Follow up commit will create nsSecureBrowserUI.
2. Fix crash in EmbedLiteSecurity
3. Create Secure Browser UI when gecko window created

### CODE REVIEW

**Comment by okodron** [comment]
Renamed `rpm/0077-sailfishos-docshell-Align-fix-parentprocess-checks.-.patch` should be also changed in spec.

**Comment by rainemak** [comment]
> Renamed `rpm/0077-sailfishos-docshell-Align-fix-parentprocess-checks.-.patch` should be also changed in spec.

Done.

**Review by okodron — APPROVED** [review]

**Comment by llewelld** [comment]
This all LGTM, and also worked nicely when tested too.

**Review by llewelld — APPROVED** [review]

**Comment by rainemak** [comment]
Rebased

**Pull request merged**
