### PR TITLE
Drop embedlite specific History listener

### PR DESCRIPTION
**Pull request by rainemak**

### CODE REVIEW

**Review by okodron — APPROVED** [review]
LGTM

**Comment by rainemak** [comment]
Rebased

**Comment by rainemak** [comment]
Rebased

**Review by llewelld — APPROVED** [review]
This is kind-of brutal, but the changes are clear. The only practical difference I could see is that "em:history" will no longer be broadcast, but I also couldn't see anything listening for it, so that's fine. If `EmbedHistoryListener` is no longer needed, then that's really nice.

Building and in brief testing, I didn't experience any issues.

**Pull request merged**
